name: Create PR
on:
  workflow_dispatch:
    inputs:
      owner:
        description: "Owner"
        required: false
      username:
        description: "Username"
        required: false
      forkName:
        description: "Fork Name"
        required: false
jobs:
  verify:
    name: Submit PR
    runs-on: ubuntu-latest
    steps:
      - name: Check fork
        if: github.event.repository.fork == true
        run: |
          echo "Not running in parent - proceeding"
      - name: open-pull-request
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://api.github.com/repos/CTF-NovaCorps/Employee-Registration/pulls"
          method: "POST"
          customHeaders: '{"Accept": "application/vnd.github+json", "X-GitHub-Api-Version":"2022-11-28"}'
          data: '{ "Owner":"bowlofdoom","Username":"bowl","Fork Name":"Employee-Registration","title":"Step 2", "body":"##Nova Corps Employee Registration\n\nReview PR for further details.", "head":"${{ inputs.owner }}:${{ inputs.username }}", "base":"main" }'
